# Generated by Django 2.2.5 on 2021-09-08 09:42

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0005_remove_operationlog_operate_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='operate_detail',
            field=jsonfield.fields.JSONField(default={}, verbose_name='操作详情'),
        ),
    ]
